import type { MarketingFlowchart } from "./marketing-flowcharts";

type Activity = { kind: "activity" | "evidence"; label: string; role: string };
type Decision = { kind: "decision"; label: string; correction: string; role?: string; correctionRole?: string };
type Stage = Activity | Decision;
type Spec = { code: string; title: string; description: string; stages: Stage[] };

const colors = { start:["#e8f8f2","#13795b"], activity:["#eaf3ff","#2563a9"], decision:["#fff4cc","#b77900"], evidence:["#f4f7fa","#52616b"], end:["#eaf7ea","#2e7d32"] } as const;
function node(id:string,kind:"start"|"activity"|"decision"|"evidence"|"end",label:string,role:string,x:number,y:number,width:number,height=76){ const [fill,stroke]=colors[kind]; return {id,kind,label,role,position:{x,y},size:{width,height:kind==="decision"?76:height},fill,stroke,textColor:"#243447"}; }
function edge(id:string,source:string,target:string,label="",sourceHandle:"top"|"right"|"bottom"|"left"="bottom",targetHandle:"top"|"right"|"bottom"|"left"="top",route:"normal"|"return"="normal"){ return {id,source,target,label,route,sourceHandle,targetHandle}; }

function makeFlow(spec:Spec):MarketingFlowchart {
  const nodes=[node(`${spec.code}-start`,"start","Inicio del subproceso","COBRANZAS",470,25,250,52)]; const edges:ReturnType<typeof edge>[]=[];
  let previous=`${spec.code}-start`, wasDecision=false, y=125;
  spec.stages.forEach((stage,index)=>{
    const id=`${spec.code}-n${index+1}`;
    if(stage.kind==="decision"){
      nodes.push(node(id,"decision",stage.label,stage.role??"COBRANZAS",350,y,520));
      edges.push(edge(`${spec.code}-e${index+1}`,previous,id,wasDecision?"Sí":""));
      const fix=`${id}-fix`; nodes.push(node(fix,"activity",stage.correction,stage.correctionRole??"COBRANZAS",20,y+118,360,86));
      edges.push(edge(`${spec.code}-e${index+1}-no`,id,fix,"No","left","top")); edges.push(edge(`${spec.code}-e${index+1}-return`,fix,id,"Regularizar","right","left","return"));
      previous=id; wasDecision=true; y+=140;
    } else { nodes.push(node(id,stage.kind,stage.label,stage.role,300,y,620,stage.kind==="evidence"?82:76)); edges.push(edge(`${spec.code}-e${index+1}`,previous,id,wasDecision?"Sí":"")); previous=id; wasDecision=false; y+=108; }
  });
  const close=`${spec.code}-close`; nodes.push(node(close,"decision","¿El caso tiene responsable, estado, próxima acción y evidencia cuando corresponde?","CONTROL DE COBRANZAS",350,y,520)); edges.push(edge(`${spec.code}-close-entry`,previous,close,wasDecision?"Sí":""));
  const fix=`${spec.code}-close-fix`; nodes.push(node(fix,"activity","Completar trazabilidad antes de cerrar el caso o el ciclo","COBRANZAS",20,y+118,360,86)); edges.push(edge(`${spec.code}-close-no`,close,fix,"No","left","top")); edges.push(edge(`${spec.code}-close-return`,fix,close,"Completar","right","left","return"));
  const end=`${spec.code}-end`; nodes.push(node(end,"end","Cierre con trazabilidad y próxima acción","EVIDENCIA",405,y+138,410,64)); edges.push(edge(`${spec.code}-close-yes`,close,end,"Sí"));
  return { code:spec.code,sourceId:spec.code,subareaCode:"ACA-S04",subareaName:"Cobranzas y Recuperación",owner:"Responsable de Cobranzas",title:spec.title,description:spec.description,context:"MOF Cobranzas y Recuperación. Toda gestión abierta conserva responsable, estado y próxima acción; los pagos son identificables y auditables.",closure:"Cierre con responsable, estado, próxima acción y evidencia cuando corresponde.",canvas:{width:1100,height:y+245},nodes,edges };
}
const A=(label:string,role="COBRANZAS"):Activity=>({kind:"activity",label,role}); const E=(label:string,role="COBRANZAS"):Activity=>({kind:"evidence",label,role}); const D=(label:string,correction:string,role="COBRANZAS",correctionRole="COBRANZAS"):Decision=>({kind:"decision",label,correction,role,correctionRole});

const specs:Spec[]=[
  {code:"ACA-COB-01",title:"Flujo maestro de Cobranzas",description:"Gestiona la cartera desde una obligación identificada hasta pago, promesa, escalamiento y control diario.",stages:[
    A("Consultar cartera del Campus e identificar participante, matrícula, concepto, monto, vencimiento, saldo y estado","CAMPUS / COBRANZAS"),A("Clasificar obligación: por vencer, vencida, comprometida, pago pendiente u observada"),A("Priorizar por antigüedad, monto, cercanía del evento y riesgo de pérdida"),D("¿La obligación tiene responsable y próxima acción?","Asignar responsable, canal, prioridad y tarea de cobranza"),A("Contactar participante por CRM, WhatsApp, correo o llamada"),A("Registrar resultado, causa, promesa y siguiente tarea"),D("¿El pago fue validado y aplicado?","Registrar promesa, causa de no pago o escalar según política"),E("Actualizar saldo, comprobante o certificado cuando corresponda y mantener trazabilidad") ]},
  {code:"ACA-COB-02",title:"Gestión de cartera y recuperación",description:"Prioriza obligaciones y realiza seguimiento de recuperación con tareas registradas.",stages:[
    A("Cargar obligaciones por vencer, vencidas y comprometidas desde Campus","CAMPUS"),A("Segmentar por antigüedad, monto, cercanía de evento y riesgo"),D("¿La obligación tiene datos de contacto y condición comercial vigentes?","Solicitar corrección a Ventas o Académica"),A("Generar tarea de cobranza y ejecutar contacto"),A("Registrar resultado, causa de no pago y próxima acción"),D("¿El caso puede continuar dentro de la gestión normal?","Escalar a Finanzas o Gerencia según política","COBRANZAS","FINANZAS / GERENCIA"),E("Actualizar estado de cartera y agenda de seguimiento") ]},
  {code:"ACA-COB-03",title:"Gestión de promesas de pago",description:"Registra, controla y resuelve promesas de pago en la misma fecha de compromiso.",stages:[
    A("Registrar monto, fecha, obligación, participante y responsable de la promesa"),A("Crear tarea automática para la fecha de compromiso"),A("En la fecha pactada, verificar pago el mismo día"),D("¿La promesa fue cumplida y el pago está validado?","Registrar promesa incumplida y gestionar nueva acción o escalamiento"),D("¿La nueva gestión está permitida por la política?","Escalar caso a Finanzas o Gerencia","COBRANZAS","FINANZAS / GERENCIA"),E("Actualizar indicador de promesas cumplidas y vencidas") ]},
  {code:"ACA-COB-04",title:"Validación y aplicación de pagos",description:"Valida que cada pago se vincule de forma segura y única con participante, matrícula y obligación.",stages:[
    A("Detectar pago desde Pagos por procesar, voucher, cuenta bancaria o canal oficial","CAMPUS / COBRANZAS"),A("Identificar participante, matrícula y obligación exacta"),D("¿El pago puede vincularse de forma segura a participante, matrícula y obligación?","Cambiar estado a Observado y abrir tarea de subsanación"),A("Validar monto, fecha, operación, cuenta recaudadora, razón social y condición comercial"),D("¿Monto y operación coinciden y no existe duplicidad?","Registrar posible duplicado u observación sin crear un segundo pago"),A("Registrar pago una sola vez y aplicar a la obligación"),D("¿El saldo y el estado se actualizaron correctamente?","Corregir aplicación y conciliar saldo"),A("Marcar pago total o parcial y actualizar cuota siguiente"),E("Registrar usuario, fecha, origen, valor, cuenta y obligación") ]},
  {code:"ACA-COB-05",title:"Pagos observados",description:"Resuelve pagos con voucher ilegible, monto inconsistente, duplicidad o identificación incompleta.",stages:[
    A("Cambiar pago a estado Observado y registrar motivo"),A("Asignar responsable y crear tarea de subsanación"),A("Comunicar causa y acción requerida el mismo día operativo"),D("¿La información faltante depende del participante?","Solicitar dato o corrección a Ventas, Académica, Finanzas u otra área dueña"),A("Recibir subsanación y validar datos"),D("¿La información ya permite validar el pago?","Mantener Observado con responsable y próxima tarea"),E("Retornar a validación de operación y registrar trazabilidad") ]},
  {code:"ACA-COB-06",title:"Comprobantes",description:"Gestiona la emisión o la observación de comprobantes sin que Cobranzas decida el criterio tributario.",stages:[
    A("Recibir pago validado"),D("¿El pago aplica para comprobante?","Marcar estado No aplica"),A("Determinar razón social, cuenta receptora y regla aprobada"),D("¿El criterio tributario está parametrizado y aprobado?","Escalar a Finanzas o Contabilidad para criterio","FINANZAS / CONTABILIDAD","FINANZAS / CONTABILIDAD"),A("Generar o gestionar boleteo o facturación","FINANZAS / CONTABILIDAD"),D("¿El comprobante fue emitido correctamente?","Marcar Observado y gestionar corrección","FINANZAS / CONTABILIDAD","FINANZAS / CONTABILIDAD"),E("Actualizar reporte de comprobantes pendientes o emitidos") ]},
  {code:"ACA-COB-07",title:"Pago de certificados",description:"Deriva pagos de certificación con un único registro financiero y confirmación de recepción.",stages:[
    A("Recibir pago validado"),D("¿El concepto corresponde a certificación?","Continuar el flujo financiero normal"),A("Marcar pago de certificado confirmado"),A("Derivar el mismo registro a Certificación sin crear un segundo ingreso","CERTIFICACIÓN"),A("Registrar fecha y hora de derivación"),D("¿Certificación confirmó la recepción el mismo día hábil?","Dar seguimiento a la derivación pendiente","CERTIFICACIÓN","CERTIFICACIÓN"),E("Actualizar estado Derivado o Recibido") ]},
  {code:"ACA-COB-08",title:"Consultas e incidencias financieras",description:"Atiende consultas financieras y deriva casos académicos sin perder el historial del ticket.",stages:[
    A("Identificar participante y matrícula"),A("Consultar información vigente en Campus","CAMPUS"),D("¿La consulta puede resolverse con información financiera vigente?","Derivar a Académica u otra área dueña sin cerrar la trazabilidad","COBRANZAS","ACADÉMICA / ÁREA DUEÑA"),A("Responder consulta financiera con información validada"),D("¿La respuesta cumple el objetivo inicial de atención?","Registrar incidencia de SLA y priorizar respuesta"),E("Mantener ticket, historial y próxima acción; objetivo de respuesta financiera menor o igual a 15 minutos") ]},
  {code:"ACA-COB-09",title:"Incidencias críticas de cobranza",description:"Registra y escala pagos no identificados, saldos inconsistentes, bloqueos o reclamos críticos.",stages:[
    A("Registrar incidencia, impacto, responsable y evidencia"),D("¿Cobranzas puede resolver dentro de su autoridad?","Escalar inmediatamente a Finanzas, área dueña o Gerencia","COBRANZAS","FINANZAS / GERENCIA"),A("Aplicar corrección conforme a política"),D("¿La corrección dejó saldo, pago y estado consistentes?","Mantener incidencia abierta y solicitar acción autorizada"),E("Adjuntar evidencia, decisión y cierre de incidencia") ]},
  {code:"ACA-COB-10",title:"Cierre diario de cobranzas",description:"Clasifica pagos, concilia operación, actualiza dashboard y notifica diferencias al terminar cada jornada.",stages:[
    A("Al fin de jornada, revisar todos los pagos conocidos del día"),D("¿Todos los pagos están clasificados como Validado, Observado o pendiente con responsable?","Clasificar faltantes y asignar responsable"),A("Revisar pagos procesados, saldos, promesas, observados, comprobantes y certificados"),D("¿Existen pagos pendientes mayores a un día sin responsable o causa?","Asignar responsable y escalar el pendiente"),A("Conciliar operación diaria y actualizar dashboard"),D("¿Existe diferencia de conciliación o riesgo?","Registrar incidencia y asignar responsable"),E("Generar cierre diario y ponerlo a disposición de Finanzas","FINANZAS") ]},
  {code:"ACA-COB-11",title:"Reporte y control de cobranzas",description:"Consolida indicadores de recuperación, mora, promesas, pagos, comprobantes y certificados para Finanzas y Gerencia.",stages:[
    A("Consolidar cobranza diaria, meta, recuperación, morosidad, promesas y pagos"),A("Calcular trazabilidad, pendientes mayores a un día, comprobantes y certificados derivados"),D("¿Existen desviaciones relevantes?","Identificar causa, tendencia, riesgo y responsable"),A("Elaborar plan de acción y presentar reporte a Finanzas","FINANZAS"),D("¿El plan requiere decisión de Gerencia?","Ejecutar seguimiento dentro de las facultades definidas","GERENCIA","COBRANZAS"),E("Registrar decisiones, responsables, fecha y próxima acción") ]},
];

export default specs.map(makeFlow);
