export type ProcessStatus = "Borrador" | "En revisión" | "Observado" | "Aprobado" | "Obsoleto";

export type Area = {
  code: string; name: string; description: string; owner: string;
  processCount: number; approved: number; color: string;
};

export type Subarea = {
  code: string; areaCode: string; name: string; description: string;
  owner: string; flow: string[]; source: "Drive" | "Propuesta" | "Usuario";
};

export type ProcessType = "Proceso" | "Tarea";

export type Process = {
  code: string; name: string; area: string; areaCode?: string; subareaCode: string; subarea: string;
  owner: string; status: ProcessStatus;
  version: string; updated: string; criticality: "Baja" | "Media" | "Alta";
  objective: string; scope: string; nextReview: string; completion: number;
  type?: ProcessType;
  tasks?: string[];
  source?: "Oficial" | "Usuario";
};

export const driveRoot = "https://drive.google.com/drive/folders/1YoIFfdcoQn107r0juIKyQk6fhaQWkT1H";

export const areas: Area[] = [
  { code: "COM", name: "Comercial", description: "Captación, seguimiento y conversión de oportunidades.", owner: "Jefatura Comercial", processCount: 18, approved: 1, color: "#00A7EB" },
  { code: "ACA", name: "Coordinación Académica", description: "Programación, ejecución académica, certificación y cobranza.", owner: "Coordinación Académica", processCount: 14, approved: 2, color: "#7E57C2" },
  { code: "GER", name: "Gerencia", description: "Planeamiento, dirección, gobierno y supervisión institucional.", owner: "Gerencia General", processCount: 53, approved: 1, color: "#01017B" },
  { code: "LOG", name: "Logística", description: "Planificación, abastecimiento, almacén y operación de eventos.", owner: "Jefatura de Logística", processCount: 6, approved: 0, color: "#D49A00" },
  { code: "MKT", name: "Marketing", description: "Campañas, contenidos y generación de demanda.", owner: "Jefatura de Marketing", processCount: 17, approved: 1, color: "#E85D75" },
  { code: "REC", name: "Recepción", description: "Atención, inscripción, caja, certificados, canales digitales y continuidad operativa.", owner: "Coordinación de Recepción", processCount: 15, approved: 1, color: "#2E8B57" },
  { code: "SIS", name: "Sistemas", description: "Plataformas, datos, accesos y continuidad tecnológica.", owner: "Jefatura de Sistemas", processCount: 2, approved: 1, color: "#4263EB" },
];

export const subareas: Subarea[] = [
  { code:"COM-S01", areaCode:"COM", name:"Prospección y leads", description:"Ingreso, calificación y asignación de oportunidades.", owner:"Coordinación Comercial", flow:["Captar oportunidad","Validar datos","Calificar lead","Asignar asesor"], source:"Propuesta" },
  { code:"COM-S02", areaCode:"COM", name:"Ventas y seguimiento", description:"Gestión de contactos, propuestas y compromisos comerciales.", owner:"Jefatura Comercial", flow:["Contactar prospecto","Identificar necesidad","Presentar propuesta","Registrar seguimiento"], source:"Propuesta" },
  { code:"COM-S03", areaCode:"COM", name:"Cierre, matrícula y convenios", description:"Formalización de ventas y transferencia del expediente.", owner:"Coordinación de Matrículas", flow:["Confirmar decisión","Validar condiciones","Registrar matrícula","Transferir expediente"], source:"Propuesta" },
  { code:"COM-S04", areaCode:"COM", name:"Jefatura de Ventas", description:"Gobierno de metas, forecast, líderes, excepciones y resultados comerciales.", owner:"Jefe de Ventas", flow:["Traducir metas comerciales","Definir reglas y umbrales","Supervisar forecast","Resolver excepciones","Presentar resultados"], source:"Drive" },
  { code:"COM-S05", areaCode:"COM", name:"Encargado / Líder Comercial", description:"Gobierno del turno, asignación operativa, SLA, relevo, equipos y coaching cotidiano.", owner:"Encargado / Líder Comercial", flow:["Abrir y organizar el turno","Asignar leads y controlar SLA","Resolver incidencias operativas","Cerrar y transferir el turno"], source:"Drive" },
  { code:"ACA-S01", areaCode:"ACA", name:"Programación académica", description:"Planificación de programas, docentes, aulas y cronogramas.", owner:"Coordinación Académica", flow:["Recibir programación","Asignar docente","Validar recursos","Publicar cronograma"], source:"Propuesta" },
  { code:"ACA-S02", areaCode:"ACA", name:"Operaciones académicas", description:"Ejecución, asistencia y seguimiento de las actividades académicas.", owner:"Responsable Académico", flow:["Aperturar sesión","Registrar asistencia","Atender incidencias","Cerrar sesión"], source:"Propuesta" },
  { code:"ACA-S03", areaCode:"ACA", name:"Certificación y calidad", description:"Verificación de requisitos, emisión y entrega de certificados.", owner:"Coordinación de Certificación", flow:["Validar requisitos","Revisar expediente","Emitir certificado","Registrar entrega"], source:"Propuesta" },
  { code:"ACA-S04", areaCode:"ACA", name:"Cobranzas y Recuperación", description:"Gestión de cartera, promesas, pagos, conciliación y reportes con trazabilidad financiera.", owner:"Responsable de Cobranzas", flow:["Priorizar cartera","Gestionar contacto","Validar pago","Conciliar y reportar"], source:"Drive" },
  { code:"GER-S01", areaCode:"GER", name:"Administración", description:"Coordinación administrativa, contratos y soporte a la gestión.", owner:"Administración", flow:["Recibir solicitud","Clasificar requerimiento","Gestionar aprobación","Cerrar atención"], source:"Drive" },
  { code:"GER-S02", areaCode:"GER", name:"Administración y Recursos Humanos", description:"Gestión de personas, contratación, asistencia y desarrollo.", owner:"Responsable de Recursos Humanos", flow:["Identificar necesidad","Seleccionar o atender","Formalizar gestión","Archivar evidencia"], source:"Drive" },
  { code:"GER-S03", areaCode:"GER", name:"Contabilidad, Finanzas y Tesorería", description:"Registro contable, control financiero, pagos y disponibilidad de caja.", owner:"Responsable de Finanzas", flow:["Recibir sustento","Validar operación","Registrar y aprobar","Pagar o conciliar"], source:"Drive" },
  { code:"GER-S04", areaCode:"GER", name:"Seguridad y Salud en el Trabajo", description:"Prevención, control y seguimiento de riesgos laborales.", owner:"Responsable de SST", flow:["Identificar peligro","Evaluar riesgo","Aplicar control","Verificar cumplimiento"], source:"Drive" },
  { code:"GER-S05", areaCode:"GER", name:"Asistentes de Gerencia", description:"Supervisión transversal, seguimiento de acuerdos, control de incidencias y reportes ejecutivos a Gerencia.", owner:"Asistente de Gerencia", flow:["Solicitar información","Verificar cumplimiento","Gestionar incidencias","Reportar a Gerencia"], source:"Drive" },
  { code:"MKT-S01", areaCode:"MKT", name:"Jefatura de Marketing", description:"Gobierno estratégico, autonomía operativa, revisión por excepción e innovación.", owner:"Jefatura de Marketing", flow:["Definir objetivos y guardrails","Coordinar ejecución autónoma","Revisar excepciones","Gestionar portafolio de innovación"], source:"Drive" },
  { code:"MKT-S02", areaCode:"MKT", name:"Coordinación / Asistencia", description:"Bandeja única, enrutamiento, SLA y calendario integrado del área.", owner:"Coordinador / Asistente", flow:["Recibir solicitud","Validar datos mínimos","Enrutar a subárea","Actualizar calendario y SLA"], source:"Drive" },
  { code:"MKT-S03", areaCode:"MKT", name:"Traffic y Performance", description:"Activación, monitoreo y optimización autónoma de campañas digitales.", owner:"Traffic y Performance", flow:["Validar checklist y guardrails","Activar campaña","Monitorear resultados","Optimizar o escalar"], source:"Drive" },
  { code:"MKT-S04", areaCode:"MKT", name:"Community Manager", description:"Parrilla, publicación, interacción, derivación de leads y gestión de crisis.", owner:"Community Manager", flow:["Preparar parrilla","Publicar contenido","Gestionar interacciones","Derivar leads o crisis"], source:"Drive" },
  { code:"MKT-S05", areaCode:"MKT", name:"Diseño Gráfico", description:"Diseño de piezas desde el brief hasta el control de calidad y entrega.", owner:"Diseño Gráfico", flow:["Validar brief","Diseñar pieza","Ejecutar QA","Entregar archivo final"], source:"Drive" },
  { code:"MKT-S06", areaCode:"MKT", name:"Producción Audiovisual", description:"Producción audiovisual completa y respaldo temporal de Diseño.", owner:"Producción Audiovisual", flow:["Recibir brief","Producir contenido","Validar técnicamente","Publicar o entregar"], source:"Drive" },
  { code:"MKT-S07", areaCode:"MKT", name:"CRM, Web y Automatización", description:"Cambios técnicos, integraciones de datos y retiro de controles paralelos.", owner:"CRM, Web y Automatización", flow:["Recibir requerimiento","Clasificar riesgo","Implementar y probar","Monitorear estabilidad"], source:"Drive" },
  { code:"MKT-S08", areaCode:"MKT", name:"RRPP, Campo y Alianzas", description:"Prospección institucional, alianzas y activaciones de campo medibles.", owner:"RRPP, Campo y Alianzas", flow:["Prospectar oportunidad","Calificar alianza o activación","Ejecutar gestión","Registrar resultados"], source:"Drive" },
  { code:"SIS-S01", areaCode:"SIS", name:"Infraestructura y soporte", description:"Atención de incidencias y continuidad de los servicios tecnológicos.", owner:"Mesa de Ayuda", flow:["Registrar incidencia","Clasificar prioridad","Resolver o escalar","Validar cierre"], source:"Propuesta" },
  { code:"SIS-S02", areaCode:"SIS", name:"Sistemas y automatización", description:"Desarrollo, integración y mejora de soluciones internas.", owner:"Jefatura de Sistemas", flow:["Recibir requerimiento","Analizar solución","Implementar cambio","Validar entrega"], source:"Propuesta" },
  { code:"SIS-S03", areaCode:"SIS", name:"Datos, seguridad y accesos", description:"Gobierno de datos, altas, bajas y control de permisos.", owner:"Responsable de Seguridad", flow:["Recibir solicitud","Validar autorización","Aplicar acceso","Auditar resultado"], source:"Propuesta" },
];

const processSeed: Process[] = [
  { code: "COM-P01", name: "Gestión de leads", area: "Comercial", subareaCode:"COM-S01", subarea:"Prospección y leads", owner: "Ana Salazar", status: "Aprobado", version: "1.2", updated: "Hoy, 09:42", criticality: "Alta", objective: "Convertir oportunidades calificadas en matrículas mediante un seguimiento oportuno y trazable.", scope: "Desde la asignación del lead hasta su conversión o descarte documentado.", nextReview: "15 mar 2027", completion: 100 },
  { code: "COM-P02", name: "Seguimiento comercial", area: "Comercial", subareaCode:"COM-S02", subarea:"Ventas y seguimiento", owner: "Luis Vega", status: "Borrador", version: "0.4", updated: "Hoy, 08:15", criticality: "Media", objective: "Estandarizar los contactos y compromisos con prospectos.", scope: "Incluye llamadas, mensajería, reuniones y registro de resultados.", nextReview: "Sin programar", completion: 62 },
  { code: "COM-P03", name: "Cierre y matrícula", area: "Comercial", subareaCode:"COM-S03", subarea:"Cierre, matrícula y convenios", owner: "Ana Salazar", status: "En revisión", version: "1.0", updated: "Ayer, 16:30", criticality: "Alta", objective: "Asegurar un cierre correcto y la transferencia del alumno a Académica.", scope: "Desde la decisión de compra hasta la entrega del expediente.", nextReview: "10 sep 2027", completion: 88 },
  { code: "COM-P04", name: "Reactivación de prospectos", area: "Comercial", subareaCode:"COM-S01", subarea:"Prospección y leads", owner: "Luis Vega", status: "Observado", version: "0.8", updated: "08 sep, 11:20", criticality: "Baja", objective: "Recuperar oportunidades inactivas con criterios homogéneos.", scope: "Prospectos sin actividad durante 30 días.", nextReview: "Sin programar", completion: 74 },
  { code: "ACA-P01", name: "Programación académica", area: "Coordinación Académica", subareaCode:"ACA-S01", subarea:"Programación académica", owner: "María Torres", status: "Aprobado", version: "2.1", updated: "09 sep, 14:10", criticality: "Alta", objective: "Planificar sesiones, docentes y recursos académicos.", scope: "Desde la apertura del programa hasta la publicación del cronograma.", nextReview: "01 mar 2027", completion: 100 },
  { code: "ACA-P02", name: "Gestión de certificación", area: "Coordinación Académica", subareaCode:"ACA-S03", subarea:"Certificación y calidad", owner: "María Torres", status: "En revisión", version: "1.5", updated: "08 sep, 18:05", criticality: "Alta", objective: "Emitir certificados válidos, completos y trazables.", scope: "Desde la verificación de requisitos hasta la entrega al alumno.", nextReview: "10 sep 2027", completion: 91 },
  { code: "ACA-P03", name: "Control de asistencia", area: "Coordinación Académica", subareaCode:"ACA-S02", subarea:"Operaciones académicas", owner: "Carlos Ríos", status: "Aprobado", version: "1.0", updated: "05 sep, 10:00", criticality: "Media", objective: "Registrar y validar la asistencia de alumnos y docentes.", scope: "Todas las sesiones sincrónicas y presenciales.", nextReview: "05 sep 2027", completion: 100 },
  { code: "MKT-P01", name: "Planificación de campañas", area: "Marketing", subareaCode:"MKT-S03", subarea:"Traffic y Performance", owner: "Valeria Cruz", status: "Aprobado", version: "1.3", updated: "09 sep, 09:12", criticality: "Media", objective: "Diseñar campañas alineadas a metas comerciales y académicas.", scope: "Desde el brief hasta la autorización de pauta.", nextReview: "09 sep 2027", completion: 100 },
  { code: "MKT-P02", name: "Community Manager", area: "Marketing", subareaCode:"MKT-S04", subarea:"Community Manager", owner: "Diego León", status: "En revisión", version: "1.5", updated: "Hace 2 h", criticality: "Media", objective: "Planificar, publicar y monitorear la comunicación en redes sociales.", scope: "Calendario, contenidos, aprobación, publicación y reporte mensual.", nextReview: "10 sep 2027", completion: 93 },
  { code: "MKT-P03", name: "Gestión de pauta digital", area: "Marketing", subareaCode:"MKT-S03", subarea:"Traffic y Performance", owner: "Valeria Cruz", status: "Observado", version: "0.9", updated: "07 sep, 12:44", criticality: "Alta", objective: "Administrar inversión digital con controles y medición de resultados.", scope: "Configuración, seguimiento, optimización y cierre de campañas.", nextReview: "Sin programar", completion: 81 },
  { code: "REC-P01", name: "Validación de pagos", area: "Recepción", subareaCode:"REC-S02", subarea:"Caja, pagos y certificados", owner: "Rosa Campos", status: "Aprobado", version: "1.1", updated: "03 sep, 15:20", criticality: "Alta", objective: "Confirmar pagos antes de habilitar servicios al alumno.", scope: "Desde la recepción del comprobante hasta la confirmación en el sistema.", nextReview: "03 mar 2027", completion: 100 },
  { code:"REC-AT-001", name:"Atención integral al visitante y participante", area:"Recepción", subareaCode:"REC-S01", subarea:"Atención, orientación e inscripción", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Atender, resolver o derivar cada necesidad con cordialidad, información oficial y trazabilidad.", scope:"Desde la apertura y revisión de canales hasta el cierre o transferencia del caso.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-INS-001", name:"Información e inscripción en Aula Virtual", area:"Recepción", subareaCode:"REC-S01", subarea:"Atención, orientación e inscripción", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Orientar e inscribir usando exclusivamente información institucional vigente.", scope:"Desde la consulta del interesado hasta la confirmación o incidencia del registro.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-CER-001", name:"Entrega de certificados", area:"Recepción", subareaCode:"REC-S02", subarea:"Caja, pagos y certificados", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Entregar certificados disponibles con identidad, firma y registro actualizados.", scope:"Desde la solicitud hasta la actualización de la herramienta compartida con Académica.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-INF-001", name:"Control de información institucional vigente", area:"Recepción", subareaCode:"REC-S01", subarea:"Atención, orientación e inscripción", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Evitar orientación con catálogos, piezas o información desactualizada.", scope:"Consulta y mantenimiento de información de eventos y programas.", nextReview:"Pendiente de aprobación", completion:88, type:"Proceso", source:"Oficial" },
  { code:"REC-OLV-001", name:"Gestión de Olva Courier", area:"Recepción", subareaCode:"REC-S03", subarea:"Gestión documentaria y courier", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Gestionar envíos, devoluciones y reenvíos con seguimiento actualizado.", scope:"Desde la llegada de courier hasta el registro de la próxima acción.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-WSP-001", name:"Atención por WhatsApp y postventa", area:"Recepción", subareaCode:"REC-S04", subarea:"Atención digital y experiencia", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Dar continuidad clara y trazable a mensajes, consultas y postventa.", scope:"Desde la revisión del historial hasta el cierre o derivación de la conversación.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-RS-001", name:"Atención y prospección en redes sociales", area:"Recepción", subareaCode:"REC-S04", subarea:"Atención digital y experiencia", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Atender oportunidades en redes respetando las frecuencias institucionales.", scope:"Actividad diaria de contactos, eventos, Inbox y derivación de interesados.", nextReview:"Pendiente de aprobación", completion:86, type:"Proceso", source:"Oficial" },
  { code:"REC-REL-001", name:"Relevo de turno, equipos y activos", area:"Recepción", subareaCode:"REC-S05", subarea:"Operación y continuidad", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Transferir pendientes, caja, equipos y activos sin pérdida de continuidad.", scope:"Desde la identificación de pendientes hasta la entrega o cierre de jornada.", nextReview:"Pendiente de aprobación", completion:92, type:"Proceso", source:"Oficial" },
  { code:"REC-STK-001", name:"Control de stock e insumos de Recepción", area:"Recepción", subareaCode:"REC-S05", subarea:"Operación y continuidad", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Asegurar materiales, chaquetas e insumos disponibles para la atención.", scope:"Control diario y requisición semanal de suministros.", nextReview:"Pendiente de aprobación", completion:86, type:"Proceso", source:"Oficial" },
  { code:"REC-FDS-001", name:"Atención presencial de fin de semana", area:"Recepción", subareaCode:"REC-S05", subarea:"Operación y continuidad", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Atender cursos y diplomados de fin de semana con caja, orientación y coordinación académica.", scope:"Desde la preparación de jornada hasta el relevo y cuadre.", nextReview:"Pendiente de aprobación", completion:90, type:"Proceso", source:"Oficial" },
  { code:"REC-CAJ-001", name:"Caja, pagos y cuadre", area:"Recepción", subareaCode:"REC-S02", subarea:"Caja, pagos y certificados", owner:"Responsable de Caja", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Controlar cobros, efectivo, POS, comprobantes y diferencias de caja.", scope:"Desde la solicitud de pago hasta el registro o entrega del cuadre.", nextReview:"Pendiente de aprobación", completion:92, type:"Proceso", source:"Oficial" },
  { code:"REC-SR-001", name:"Sugerencias y reclamos", area:"Recepción", subareaCode:"REC-S04", subarea:"Atención digital y experiencia", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Registrar, resolver o derivar sugerencias y reclamos con seguimiento.", scope:"Desde la recepción hasta el cierre documentado o pendiente trazable.", nextReview:"Pendiente de aprobación", completion:88, type:"Proceso", source:"Oficial" },
  { code:"REC-MP-001", name:"Mesa de partes y documentos externos", area:"Recepción", subareaCode:"REC-S03", subarea:"Gestión documentaria y courier", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Media", objective:"Registrar y derivar documentos externos de forma ordenada y trazable.", scope:"Desde la recepción del documento hasta la derivación y conservación de evidencia.", nextReview:"Pendiente de aprobación", completion:86, type:"Proceso", source:"Oficial" },
  { code:"REC-CH-001", name:"Cambio de turno y cierre de jornada", area:"Recepción", subareaCode:"REC-S05", subarea:"Operación y continuidad", owner:"Personal de Recepción", status:"Borrador", version:"1.0", updated:"Manual de Recepción", criticality:"Alta", objective:"Asegurar control transversal de pendientes, activos, canales y cierre diario.", scope:"Desde la revisión de caja y canales hasta la confirmación del cambio de turno.", nextReview:"Pendiente de aprobación", completion:92, type:"Proceso", source:"Oficial" },
  { code: "SIS-P01", name: "Alta y baja de accesos", area: "Sistemas", subareaCode:"SIS-S03", subarea:"Datos, seguridad y accesos", owner: "Jorge Paz", status: "Aprobado", version: "2.0", updated: "02 sep, 17:10", criticality: "Alta", objective: "Gestionar accesos de forma segura y oportuna.", scope: "Personal, docentes, proveedores y usuarios temporales.", nextReview: "02 mar 2027", completion: 100 },
  { code: "SIS-P02", name: "Gestión de incidencias", area: "Sistemas", subareaCode:"SIS-S01", subarea:"Infraestructura y soporte", owner: "Jorge Paz", status: "En revisión", version: "1.1", updated: "01 sep, 09:35", criticality: "Media", objective: "Restaurar servicios según prioridad e impacto.", scope: "Registro, clasificación, atención, escalamiento y cierre.", nextReview: "10 sep 2027", completion: 89 },
  { code: "LOG-P01", name: "Requerimiento y planificación de eventos", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Alta", objective: "Planificar los requerimientos de eventos con demanda, capacidad, reservas y trazabilidad.", scope: "Desde la programación académica hasta la liberación de picking por evento.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "LOG-P02", name: "Proceso de compras", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Alta", objective: "Adquirir bienes y servicios mediante requerimiento, evaluación, recepción conforme y expediente financiero.", scope: "Desde la necesidad validada hasta el cierre de compra y evaluación del proveedor.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "LOG-P03", name: "Recepción, almacenamiento e inventario", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Alta", objective: "Controlar el ingreso, ubicación, conservación y disponibilidad del inventario institucional.", scope: "Desde la recepción conforme hasta el tratamiento de alertas o diferencias de inventario.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "LOG-P04", name: "Picking, packing y operación de evento", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Alta", objective: "Preparar, montar, soportar y cerrar cada evento con controles de calidad y evidencia.", scope: "Desde el checklist liberado D-3/D-2 hasta el cierre D+1.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "LOG-P05", name: "Logística inversa", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Media", objective: "Recuperar, clasificar y conciliar recursos retornados luego de cada evento.", scope: "Desde el retorno del evento hasta el cierre de kardex, mantenimiento y acciones por diferencias.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "LOG-P06", name: "Operación de sábado y domingo", area: "Logística", areaCode:"LOG", subareaCode:"LOG", subarea:"Logística", owner: "Jefatura de Logística", status: "Borrador", version: "0.1", updated: "MOF 2026", criticality: "Alta", objective: "Asegurar cobertura de fin de semana según la carga operativa y el nivel de simultaneidad.", scope: "Desde el cierre del plan de fin de semana hasta el cierre operativo del lunes D+1.", nextReview: "Pendiente de aprobación", completion: 85, type: "Proceso", source: "Oficial" },
  { code: "GER-P01", name: "Aprobación de presupuesto", area: "Gerencia", subareaCode:"GER-S03", subarea:"Contabilidad, Finanzas y Tesorería", owner: "Gerencia General", status: "Aprobado", version: "1.0", updated: "25 ago, 11:15", criticality: "Alta", objective: "Asegurar decisiones presupuestales consistentes y documentadas.", scope: "Solicitudes extraordinarias y presupuesto anual.", nextReview: "25 feb 2027", completion: 100 },
];

export const processes: Process[] = processSeed.map((process) => process.area === "Recepción"
  ? { ...process, areaCode: "REC", subareaCode: "REC", subarea: "Recepción" }
  : process,
);
export const reviews = processes.filter((process) => ["En revisión", "Observado"].includes(process.status));
export const statusTone: Record<ProcessStatus, string> = { "Borrador": "draft", "En revisión": "review", "Observado": "observed", "Aprobado": "approved", "Obsoleto": "obsolete" };
export function getProcess(code: string) { return processes.find((process) => process.code.toLowerCase() === code.toLowerCase()); }
export function getArea(code: string) { return areas.find((area) => area.code.toLowerCase() === code.toLowerCase()); }
export function getSubareas(areaCode: string) { return subareas.filter((subarea) => subarea.areaCode === areaCode); }
export function mergeSubareas(official: Subarea[], stored: Subarea[]) {
  const byCode = new Map(official.map((subarea) => [subarea.code, subarea]));
  const nextNumber = new Map<string, number>();
  official.forEach((subarea) => {
    const number = Number(subarea.code.match(/-S(\d+)$/)?.[1] ?? 0);
    nextNumber.set(subarea.areaCode, Math.max(nextNumber.get(subarea.areaCode) ?? 0, number));
  });
  stored.forEach((subarea) => {
    const current = byCode.get(subarea.code);
    if (!current) {
      byCode.set(subarea.code, subarea);
      return;
    }
    if (subarea.source !== "Usuario" || current.name === subarea.name) return;
    const number = (nextNumber.get(subarea.areaCode) ?? 0) + 1;
    nextNumber.set(subarea.areaCode, number);
    const code = `${subarea.areaCode}-S${String(number).padStart(2, "0")}`;
    byCode.set(code, { ...subarea, code });
  });
  return Array.from(byCode.values());
}

export function mergeProcesses(official: Process[], stored: Process[]) {
  const byCode = new Map(official.map((process) => [process.code.toLowerCase(), process]));
  stored.forEach((process) => {
    byCode.set(process.code.toLowerCase(), process);
  });
  return Array.from(byCode.values());
}
