"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Download, ExternalLink, FileSpreadsheet, FileText, History, MessageSquareText, Pencil, Send, ZoomIn } from "lucide-react";
import { StatusBadge } from "@/components/status-badge";
import { driveRoot, Process, ProcessStatus } from "@/lib/data";

const tabs=["Diagrama","Ficha","KPI","Documentos","Historial"] as const;
type Tab=typeof tabs[number];

export function ProcessDetail({process}:{process:Process}){
  const [tab,setTab]=useState<Tab>("Diagrama"); const [status,setStatus]=useState<ProcessStatus>(process.status); const [notice,setNotice]=useState("");
  const transition=(next:ProcessStatus,message:string)=>{setStatus(next);setNotice(message);window.setTimeout(()=>setNotice(""),3500)};
  return <>
    {notice&&<div className="pilot-banner" role="status"><CheckCircle2 size={17}/><span>{notice} <strong>El cambio es local en el modo piloto.</strong></span></div>}
    <div className="detail-top"><div><div className="breadcrumb"><Link href="/biblioteca">Biblioteca</Link> / <Link href={`/areas/${process.subareaCode.slice(0,3)}`}>{process.area}</Link> / <Link href={`/areas/${process.subareaCode.slice(0,3)}/${process.subareaCode}`}>{process.subarea}</Link> / <span>{process.code}</span></div><div className="detail-title-line"><span className="detail-code">{process.code}</span><h1>{process.name}</h1><StatusBadge status={status}/></div><p className="detail-meta">Dueño: {process.owner} · Versión {process.version} · Actualizado {process.updated}</p></div><div className="detail-actions"><a className="button button-secondary" href={driveRoot} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Abrir Drive</a>{status==="Borrador"||status==="Observado"?<button className="button button-primary" onClick={()=>transition("En revisión","Proceso enviado a revisión.")}><Send size={15}/> Enviar a revisión</button>:status==="En revisión"?<><button className="button button-secondary" onClick={()=>transition("Observado","Proceso observado y devuelto al editor.")}><MessageSquareText size={15}/> Observar</button><button className="button button-primary" onClick={()=>transition("Aprobado","Versión aprobada y congelada.")}><CheckCircle2 size={15}/> Aprobar</button></>:null}</div></div>
    <div className="tabs" role="tablist" aria-label="Secciones del proceso">{tabs.map((item)=><button key={item} className={`tab ${tab===item?"active":""}`} onClick={()=>setTab(item)} role="tab" aria-selected={tab===item}>{item}</button>)}</div>
    <div className="card detail-panel">
      {tab==="Ficha"&&<div className="summary-grid"><div><section className="summary-section"><h3>Objetivo</h3><p>{process.objective}</p></section><section className="summary-section"><h3>Alcance</h3><p>{process.scope}</p></section><section className="summary-section"><h3>Entradas y salidas</h3><p><strong>Entradas:</strong> solicitud o evento de inicio, datos completos y documentos de soporte.<br/><strong>Salidas:</strong> resultado validado, evidencia registrada y notificación a la siguiente área.</p></section><section className="summary-section"><h3>Participantes</h3><p>Dueño del proceso · Responsable operativo · Revisor del área · Aprobador según criticidad.</p></section></div><aside className="facts"><div className="fact"><span>Área propietaria</span><strong>{process.area}</strong></div><div className="fact"><span>Subárea</span><strong>{process.subarea}</strong></div><div className="fact"><span>Criticidad</span><strong>{process.criticality}</strong></div><div className="fact"><span>Nivel</span><strong>N2 · Operativo</strong></div><div className="fact"><span>Tipo</span><strong>Soporte / gestión</strong></div><div className="fact"><span>Versión institucional</span><strong>v{process.version}</strong></div><div className="fact"><span>Próxima revisión</span><strong>{process.nextReview}</strong></div><div className="fact"><span>Ficha completa</span><strong>{process.completion}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${process.completion}%`}}/></div></aside></div>}
      {tab==="Diagrama"&&<div className="diagram-wrap"><div className="diagram-toolbar"><p>Vista de lectura de la versión vigente. La edición se abre como un modo separado.</p><div style={{display:"flex",gap:8}}><button className="button button-secondary"><ZoomIn size={15}/> Ampliar</button><Link className="button button-primary" href={`/areas/${process.subareaCode.slice(0,3)}/${process.subareaCode}`}><Pencil size={15}/> Abrir subárea</Link></div></div><div className="diagram-canvas"><div className="flow"><div className="flow-node start">Inicio</div><ArrowRight className="flow-arrow"/><div className="flow-node">Registrar solicitud</div><ArrowRight className="flow-arrow"/><div className="flow-node">Validar información</div><ArrowRight className="flow-arrow"/><div className="flow-node decision"><span>¿Información completa?</span></div><ArrowRight className="flow-arrow"/><div className="flow-node">Ejecutar actividad</div><ArrowRight className="flow-arrow"/><div className="flow-node end">Cerrar proceso</div></div></div></div>}
      {tab==="Documentos"&&<div><div className="card-header"><div><h2>Documentos relacionados</h2><p>Drive conserva los archivos oficiales; el portal conserva sus metadatos.</p></div><a className="button button-primary" href={driveRoot} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Ver carpeta</a></div><div className="document-list"><div className="document-row"><div className="doc-icon"><FileText size={18}/></div><div><strong>{process.code}_{process.name.replaceAll(" ","_")}_v{process.version}_APROBADO.pdf</strong><span>Publicación oficial · PDF · Versión {process.version}</span></div><button className="button button-secondary"><Download size={14}/> Descargar</button></div><div className="document-row"><div className="doc-icon"><FileSpreadsheet size={18}/></div><div><strong>{process.code}_Checklist_operativo.xlsx</strong><span>Documento de trabajo · Hoja de cálculo</span></div><button className="button button-secondary"><ExternalLink size={14}/> Abrir</button></div></div></div>}
      {tab==="KPI"&&<div className="summary-grid"><div><section className="summary-section"><h3>Cumplimiento del proceso</h3><div className="kpi-value">92%</div><p>Casos completados dentro del estándar definido durante el periodo.</p></section><div className="bar-chart">{[48,62,58,74,69,81,92].map((height,index)=><div className="bar" style={{height:`${height}%`}} key={index}/>)}</div></div><aside className="facts"><div className="fact"><span>Frecuencia</span><strong>Mensual</strong></div><div className="fact"><span>Meta</span><strong>≥ 90%</strong></div><div className="fact"><span>Responsable</span><strong>{process.owner}</strong></div><div className="fact"><span>Fuente</span><strong>Registro operativo</strong></div></aside></div>}
      {tab==="Historial"&&<div><div className="card-header"><div><h2>Trazabilidad</h2><p>Eventos relevantes del proceso y sus versiones.</p></div></div><div className="activity-list"><div className="activity-item"><strong>Versión {process.version} actualizada</strong><span>{process.owner} · {process.updated}</span></div><div className="activity-item"><strong>Revisión documental solicitada</strong><span>Responsable del proceso · 08 sep, 16:40</span></div><div className="activity-item"><strong>Versión anterior congelada</strong><span>Administrador de Procesos · 02 sep, 10:15</span></div><div className="activity-item"><History size={13}/> <strong>Proceso creado</strong><span>Catálogo inicial · 15 ago, 09:00</span></div></div></div>}
    </div>
  </>;
}
